### ISSUE TITLE
jx3-minikube jx admin-operator field with this  issue 

### ISSUE THREAD

**Issue by prashanthpantula** [jx3-gitops-repositories/jx3-minikube-vault#5]
i got this issue error: unable to recognize "config-root/namespaces/jx/docker-registry/docker-registry-ingress.yaml": no matches for kind "Ingress" in version "extensions/v1beta1"
mutatingwebhookconfiguration.admissionregistration.k8s.io/webhook.pipeline.tekton.dev unchanged
make[1]: Leaving directory '/workspace/source'
make[1]: *** [versionStream/src/Makefile.mk:290: kubectl-apply] Error 1
error: failed to regenerate: failed to regenerate phase 1: failed to run 'make regen-phase-1' command in directory '.', output: ''
make: *** [versionStream/src/Makefile.mk:242: regen-check] Error 1
boot Job pod jx-boot-959b52a5-fdf9-4caf-83ac-b75c5287dcad-nfcpq has Failed
error: boot Job pod jx-boot-959b52a5-fdf9-4caf-83ac-b75c5287dcad-4n8g9 has Failed

**Comment by eyupdzhanY1** [comment]
Hello, How did you solve this issue  ?

**Comment by saiprashanthpantula** [comment]
I did resolve by using old kuberentes version like 1.21 while installing minikube .
